### ISSUE TITLE
Receiving events

### ISSUE THREAD

**Issue by rolftimmermans** [cetra3/tmq#10]
I'm trying to set up socket monitoring with `.monitor(..)` on a socket builder.

However I am stuck because there seems to be no `ZMQ_PAIR` socket type to connect to the monitoring socket that `libzmq` sets up.

How can I receive socket events with `tmq`?

**Comment by cetra3** [comment]
That's a good question, I am assuming that the pair socket type hasn't been implemented yet! Happy to accept a PR here. 

In the interim you should be able to use a background thread and the standard zeromq crate as long as it's the same `Context`

**Comment by cetra3** [comment]
Just updating this: I have published a new version `0.2.1` with your implementation.  Thanks for the PR!
