### ISSUE TITLE
Bump mio dependency to 0.7 to get rid of net2 dependency

### ISSUE THREAD

**Issue by clintfred** [cetra3/tmq#12]
See https://rustsec.org/advisories/RUSTSEC-2020-0016.html

Since there isn't a 0.6.x version of mio that doesn't have `net2`, there may be other breaking changes to absorb.

**Comment by cetra3** [comment]
I think we might need to wait until `tokio` itself uses mio `0.7`.

**Comment by clintfred** [comment]
Here's the [tokio mio 0.7 issue](https://github.com/tokio-rs/tokio/issues/1190) for reference

**Comment by cetra3** [comment]
@clintfred can you confirm if this has been resolved in tokio 1.0? I have just merged [this PR](https://github.com/cetra3/tmq/pull/19)  If so can you close off this issue.

**Comment by clintfred** [comment]
Since #19 removed the direct dependency on mio, and tokio 1.0.1 depends on mio 0.7.7 (which doesn't use net2), I think everything should be good. 

Thanks!

Curious: why was the direct dependency on on mio able to be removed?

**Comment by skrap** [comment]
> Curious: why was the direct dependency on on mio able to be removed?

Tokio 1.0 has an API (`AsyncFd`) which allows it to integrate a raw file descriptor into the event loop.  I think it's just implemented in `mio` internally within Tokio.  This was done to avoid an API dependency on the interface to as-yet-not-stabilized `mio` crate.

**Comment by cetra3** [comment]
Yep as @skrap mentioned we could use tokio itself to implement the glue rather than having to use mio.  I'll close this issue off.
