### ISSUE TITLE
0.3.0 Release?

### ISSUE THREAD

**Issue by clintfred** [cetra3/tmq#23]
Apologies if this is covered in a roadmap doc somewhere, but with tokio 1.x support now merged, is it time to release 0.3.0? Or are there other features/fixes you're waiting for?
I would also suggest a CHANGELOG.md be added when going to 0.3.0 to make it clear what changes are in various releases and what features exist but have not yet been released.

Thanks for tmq. It's great!

**Comment by cetra3** [comment]
No reason actually! thanks for reminding me, I have tagged & pushed `0.3.0` to crates
