### ISSUE TITLE
Calling subscribe multiple times doesn't seem possible

### ISSUE THREAD

**Issue by kootenpv** [cetra3/tmq#24]
I know with plain zmq it is possible to have multiple subscriptions, but I suppose here it is not possible?

For example:

```rust
let mut socket = subscribe(&Context::new())
    .connect("tcp://127.0.0.1:7899")?
    .subscribe(b"topic")?
    .subscribe(b"topic2")?;
```

Basically would like to loop over a vec of topics and subscribe to those specific ones (rather than subscribing to all, i.e. `b""`)

After one subscribe the `SubscribeWithoutTopic` changes into `Subscribe` whereas the latter cannot do more subscriptions?

**Comment by cetra3** [comment]
Good catch, we may need to rework the subscribe API to make this possible, maybe even have the `subscribe` function accept an iterator or similar.  Open to PRs!
