### ISSUE TITLE
Help: Get started with multiple publishers&subscribers

### ISSUE THREAD

**Issue by jbbjarnason** [cetra3/tmq#3]
Hi, this is more of a question rather than an issue, please feel free to close if this is unwanted or a stupid question.

Small intro: My project objective is to implement type-specific IPC wrapper. 
I have no experience in Rust, I have only studied it for a week or so but I am amazed by the cargo compiling mechanism and memory handling.

So to the question, I would like to create multiple subscription handlers with different topics and multiple publisher(or one publisher sending multiple topics) in startup and at runtime(after the loop has started). I am not sure how to create the tokio::run loop.
Do you got any code that I could refer to or throw in a short example(does not have to be complete)? 

Regards, Jón Bjarni

**Comment by cetra3** [comment]
`tokio::spawn` is probably what you're after: you can spawn background tasks with it. [https://tokio.rs/docs/futures/spawning/](https://tokio.rs/docs/futures/spawning/).  

You can combine this with the `lazy` future to spawn a few background tasks then return a future to tokio.

```
tokio::run(lazy(|| {
   //setup other futures here:
   tokio::spawn(publish.....);
   tokio::spawn(publish.....);

    subscribe(&Context::new())
        .connect("tcp://127.0.0.1:7899")
        .expect("Couldn't connect")
        .subscribe("")
        .for_each(|val| {
            info!("Subscribe: {}", val.as_str().unwrap_or(""));
            Ok(())
        })
        .map_err(|e| {
            error!("Error Subscribing: {}", e);
        })
}))
````

This is probably outside the scope of `tmq`, so I'll close this ticket off :)
