### ISSUE TITLE
musl builds broken

### ISSUE THREAD

**Issue by skeet70** [cetra3/tmq#36]
`musl` builds are broken currently (tested on an M1 Mac running a docker Alpine image and Ubuntu github action runners running Alpine docker images).

I opened upstream issues with more detail [here](https://github.com/erickt/rust-zmq/issues/359) and [here](https://github.com/jean-airoldie/zeromq-src-rs/issues/21) but pinning the dependency `zmq = "<0.10.0"` would also fix the problem for us as a downstream user. As long as I'm aware of it, I'll be sure to close this issue once there's an upstream fix that is automatically consumed by the current dependency setting.

**Comment by cetra3** [comment]
Ah that's an interesting one & I'm surprised the existing versioning doesn't work for it:

I.e, I would've thought that this equivalent to `<0.10.0`:

```
zmq = ">=0.9.2"
```

Not sure if changing that would introduce a breaking change

**Comment by skeet70** [comment]
I would've also thought that based on [the documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio), as our only explicit dependency is on `tmp = "0.3"`.

I think this may actually be a non-issue. When I build the project locally from scratch it does only install `0.9.2`. This must be an issue with an overactive dependabot doing something different with semver than Rust does.
